services:
  - type: web
    name: youtube-scraper
    env: python
    buildCommand: pip install -r requirements.txt && playwright install
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
